#!/usr/bin/env bash
# Configures a new Ubuntu machine to act as a load balancer

# Update packages
sudo apt -y update

# Enable dedicated PPA
#sudo apt -y install --no-install-recommends software-properties-common
#sudo add-apt repository ppa:vbernat/haproxy-2.0

# Install HAproxy
sudo apt -y install haproxy

# Configure HAproxy
echo "frontend haproxy-main
	bind *:80
	default_backend ninis_servers

backend ninis_servers
	balance roundrobin
	server 398697-web-01 34.229.184.178:80 check
	server 398697-web-02 54.83.138.88:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart haproxy
sudo service haproxy restart
