#!/usr/bin/env bash
# Backs up a MySQL database
if [ "$#" -eq 0 ]; then
	echo "Usage: $0 <password>"
	exit 1
fi

BACKUP_FILE="backup.sql"

# Run mysqldump command
if ! mysqldump -uroot -p"$1" --all-databases > "$BACKUP_FILE"; then 
	echo "mysqldump failed"
	exit 1
fi

# Create archive of backup
DATE=$(date +%d-%m-%Y)
tar -czf "$DATE.tar.gz" "$BACKUP_FILE"
if ! tar -czf "$DATE.tar.gz" "$BACKUP_FILE"; then
	echo "Archive creation failed"
	exit 1
fi

echo "Archive created succesfully"
