#!/usr/bin/env bash
# Script pings an IP address passed as an argument to it 5 times

# Checks that script receives an argument
if [ "$#" -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

# Ping IP address
IP_ADDRESS="$1"
ping -c 5 "$IP_ADDRESS"
