#!/usr/bin/env bash
# Script pings an IP address passed as an argument to it 5 times

# Checks that script receives an argument
if [ "$#" -eq 0 ]; then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi

# Ping IP address
ping -c 5 "$1"
