#!/usr/bin/env bash
# Script fixes a server to have nginx installed and configured to listen on port 80
# Update packages
sudo apt -y update

# Intall nginx
sudo apt -y install nginx

# Start nginx
sudo service nginx start
