#!/usr/bin/env bash
# Script fixes what's keeping Ubuntu container's Nginx configuration from listening on port 80

## Curl the server to see if Nginx works
#if curl 0:80; then
#	exit
#fi

# Check if Nginx is installed and running
if ! sudo service nginx status; then
	sudo apt -y update
	sudo apt install -y nginx
	sudo apt install -y ufw
	sudo ufw allow 'HTTP Nginx'
	sudo service nginx start
fi

# Check if Nginx is listening on port 80
sudo apt install -y net-tools
if ! sudo netstat -lpn | grep nginx | grep -q 0:80; then
	sudo apt install -y ufw
	sudo ufw allow 80/tcp
	sudo service nginx restart
fi
