#!/usr/bin/env bash
# Configures ufw to block all incoming traffic except to ports 80,443 and 22.

# Install ufw
sudo apt update -y
sudo apt install -y ufw

# Deny all incoming traffic except those specifically allowed
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Reload and enable firewall
sudo ufw enable -y
