#!/usr/bin/env bash
# Script configures an Ubuntu server with certain requirements

# Make copy of /etc/hosts file
cp /etc/hosts /etc/hosts.tmp

# Resolve localhost to 127.0.0.2 in temporary hosts file
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/host.tmp

# Resolve facebook.com to 8.8.8.8 in temporary hosts file
NEW_SITE="facebook.com\t8.8.8.8"
sed -i "/localhost/a ${NEW_SITE}" /etc/hosts.tmp

# Copy temporary hosts file into /etc/hosts file
mv -f /etc/hosts.tmp /etc/hosts

# Delete temporary hosts file
rm /etc/hosts.tmp
