#!/usr/bin/env bash
# Get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it
docker run -p 8080:80 -d -ti holbertonschool/265-0
docker exec holbertonschool/265-0 sed -i '	/DocumentRoot /a DirectoryIndex index.html' /etc/apache2/sites-available/000-default.conf
docker exec holbertonschool/265-0 service apache2 restart
