#!/usr/bin/env bash
# Script configures ubuntu container to meet the following requirements
# - nginx running as 'nginx' user
# - nginx must be listening on all active IPs on port 8080

# Reconfigure nginx to listen on port 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Modify commented user directive
sudo sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf

# Modify permissions of nginx config file to allow
chmod 644 /etc/nginx/nginx.conf

# Run nginx as nginx user
sudo -u nginx service nginx start
