#!/usr/bin/env bash
# Script configures ubuntu container to requirements in 1-run_nginx_as_nginx but shorter
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
